apiVersion: v1
kind: Service
metadata:
  name: eginmusic
  labels:
    app: eginmusic
spec:
  type: NodePort
  selector:
    app: eginmusic
  ports:
    - port: 8000
      nodePort: 30009
      protocol: TCP
      targetPort: 8000
