apiVersion: apps/v1
kind: Deployment
metadata:
  name: eginmusic
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: kannarajesh064/eginmusic:tagname
          name: django
          ports:
            - containerPort: 8000
              name: eginmusic
